when:
  event: [manual, push, pull_request]
  branch: main
  path: [.woodpecker/lint.yaml, renovate.json, .justfile, Dockerfile, "**/*.yaml", "**/*.md"]

steps:

  renovate:
    image: kokuwaio/renovate-config-validator:43
    depends_on: []
    when: [path: [.woodpecker/lint.yaml, renovate.json]]

  just:
    image: kokuwaio/just:1.46.0
    depends_on: []
    when: [path: [.woodpecker/lint.yaml, .justfile]]

  dockerfile:
    image: kokuwaio/hadolint:v2.14.0
    depends_on: []
    when: [path: [.woodpecker/lint.yaml, Dockerfile]]

  yaml:
    image: kokuwaio/yamllint:v1.38.0
    depends_on: []
    when: [path: [.woodpecker/lint.yaml, "**/*.yaml"]]

  markdown:
    image: kokuwaio/markdownlint:0.47.0
    depends_on: []
    when: [path: [.woodpecker/lint.yaml, "**/*.md", .markdownlint.yaml]]
