when:
  event: pull_request
  path: [.woodpecker/verify.yaml, Dockerfile, Cargo.toml, Cargo.lock, src/**]

steps:

  image:
    image: kokuwaio/buildctl:v0.26.3
    depends_on: []
    settings:
      platform: [linux/amd64, linux/arm64]
      build-args:
        RUSTUP_DIST_SERVER: ${RUSTUP_DIST_SERVER}
        RUSTUP_UPDATE_ROOT: ${RUSTUP_UPDATE_ROOT}

  rust:
    image: rust:1.92.0-slim-bookworm
    depends_on: []
    commands: [rustup component add rustfmt, cargo fmt --all --check]
    when: [path: {exclude: [Dockerfile]}]
